name: CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  Regression:
    if: (github.event.review.state == 'approved') && (github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    
    container:
      image: public.ecr.aws/certora/cvt-image:2024.10.23-4499-c4f8ad4
    
    env:
      ETHSCAN_API_KEY: ${{ secrets.ETHSCAN_API_KEY }}
      QUORUM_PATH: "."
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Quorum Repo
      run: pip3.11 install .

    - name: Execute Regression Tests
      run: |
        pytest Quorum/tests --maxfail=1 --disable-warnings --tb=short
        CheckProposal --config Quorum/execution.json

  
  Update-Version:
    if: (github.event.review.state == 'approved') && (github.event.pull_request.base.ref == 'main')
    needs: Regression
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Change version
        run: python3 -c "from datetime import datetime; print(datetime.now().strftime('%Y%m%d.%H%M%S.%f'))" > version
      
      - name: Configure Git
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

      - name: Commit and push version change
        env:
            GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git add .
          git commit -m "Auto change version."
          git push origin HEAD:$GITHUB_HEAD_REF -f
