name: Update-Version

on:
  pull_request:
    branches:
      - main

jobs:
  Update-Version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Change version
      run: python3 -c "from datetime import datetime; print(datetime.now().strftime('%Y%m%d.%H%M%S.%f'))" > version
    
    - name: Configure Git
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"

    - name: Commit and push version change
      run: |
        git add .
        git commit -m "Auto change version."
        git push origin HEAD:$GITHUB_HEAD_REF -f